---

- name: Update System Package Cache
  apt: update_cache=yes
  sudo: yes

- name: Upgrade System Packages
  apt: upgrade=full

- name: Rebooting if needed...
  command: shutdown -r now removes=/var/run/reboot-required
  async: 0
  poll: 0
  ignore_errors: true
  register: restarted

- name: Waiting for reboot...
  pause:
    seconds: 250
  when: restarted.changed
