---

- name: "Download scripts"
  get_url:
   url: http://sohani.me/scripts/nginx-latest.sh
   dest: /usr/local/src/nginx-latest.sh

- name: "change permission"
  file:
   path: /usr/local/src/nginx-latest.sh
   mode: 0777

- name: run scripts
  shell: /usr/local/src/nginx-latest.sh

- name: Unarchive a file that is already on the remote machine
  unarchive:
   src: /usr/local/src/nginx.tar.gz
   dest: /usr/local/src/
   copy: no

- name: "Compile Nginx"
  shell: cd /usr/local/src/nginx-* && ./configure --prefix=/usr/local/nginx --sbin-path=/usr/local/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=webapp --group=webapp --with-threads  --without-http_rewrite_module --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_image_filter_module --with-http_sub_module --with-http_gunzip_module --with-http_gzip_static_module --with-pcre --with-http_stub_status_module  --with-http_v2_module  && make && make install

- name: copy file systemd
  template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service

- name: "start nginx"
  systemd:
    name: nginx
    enabled: yes
    state: restarted

- name: copy file conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: restart service nginx
  systemd:
   name: nginx
   state: restarted
